### ISSUE TITLE
Not working with KSP 1.2.2 and RSS, need help!

### ISSUE THREAD

**Issue by Swarl3s** [Sigma88/Galactic-Neighborhood#27]
Hey there i hope somebody could help me with my problem :)

I already got the RealSolarSystem(+8192textures) Mod installed and everything worked fine. Then i wanted to try something new and installed the Galactic Neighborhood Mod together with SigmaDimensions like recommended. 

Mods also installed: Kopernicus, ModularFlightIntergrator, Module Manager

But after starting KSP it seems like RealSolarSystem is not longer working along with the other mods.

In the menu for example there only is the normal Kerbin in the background. And in the Tracking Station something strange happens: For a second or so i can see the Earth from RSS, but then the planet disappears, the camera seems to quickly move up a little (like it does when you switch between planets) then showing the stock Kerbin

Everything else of the Galactic Neighborhood seems to work just fine, all new stars appear in the tracking station. (And yes i searched the whole rest of the galaxy cause i was hoping to find the rss somewhere else :D)

Things i've tried so far: 

-try to launch without SigmaDimensions > No difference
-tried it with another solar system instead of RSS (named 'Other World') > doesn't appear at all, still only kerbin, so same problem

Without Galactic Neighborhood the RSS and OtherWorld Mods work fine
All Mods are updated to latest versions, and got installed into a clean KSP Version!

These are the current versions i use:
-GalacticNeighborhood 0.3.1
-RealSolarSystem v.12.0
-SigmaDimensions 0.7.4
-ModuleManager 2.7.5
-Kopernicus 1.2.2-5 (incl.ModularFlightIntergrator)

Hope somebody can help me! If any log files are needed, just tell me where i can find them and how to send them

P.S.: Sorry if my english isn't the best, i normally speak german :p

**Comment by Sigma88** [comment]
sorry I just noticed this 
is the problem resolved? or did you just give up?

I can take a look if you are still having this issue

**Comment by Swarl3s** [comment]
Hey sigma and thanks for your reply!

The problem was resolved cause there never was on. I thought that i can use RSS to replace Kerbin, and then additional install GalacticNeighborhood to get some new SolarSystems beside the main system (the rss)

I didn't know that if i'm using both mods the main system stays stock and the rss gets placed somewhere else. 
I was hoping i still could use the RSS as the main system, but it seems like this isn't possible?

Sorry for my terrible english i'm doing my best to keep it understandable :)
@Sigma88

**Comment by Sigma88** [comment]
it would require making a modulemanager patch specific for what you want, I don't have the time to do it for you, but it's not technically impossible to do.
you can try to ask on the forums if there's someone willing to help you
