### ISSUE TITLE
Proposed Planet Packs

### ISSUE THREAD

**Issue by Sigma88** [Sigma88/Galactic-Neighborhood#29]
| Planet Pack | Star Name | Star Type | Analogue | Status |
|--------------|-------------|-----------|------------|--------|
|[Before Kerbin](https://forum.kerbalspaceprogram.com/index.php?/topic/164477-0/)| Arkos | G2 V | [Early Sun](https://en.wikipedia.org/wiki/Sun#Main_sequence) | Ready |
|[Kolyphemus](https://forum.kerbalspaceprogram.com/index.php?/topic/160140-0/)| Avtur | M6.5&nbsp;V | [CN Leonis](https://en.wikipedia.org/wiki/Wolf_359) | Ready |
|[Suthe](forum.kerbalspaceprogram.com/index.php?/topic/158178-/)| Suthe| M3.5 V | [AD Leo](https://en.wikipedia.org/wiki/AD_Leonis)| Ready |
|[After Kerbin](https://forum.kerbalspaceprogram.com/index.php?/topic/165166-0/)| Arkel | ? | [HBS](https://arxiv.org/pdf/0801.4031.pdf)| Ready |
|[Other_Worlds_Reboot](https://forum.kerbalspaceprogram.com/index.php?/topic/164146-0/)| Cercani | K5 V | [61 Cyg A](https://en.wikipedia.org/wiki/61_Cygni) | Ready |
|[(Almost)RealSolarSystem](https://forum.kerbalspaceprogram.com/index.php?/topic/167867-0/)| ? | ? | ? | In Progress |
|[Imperial Planet Pack](https://forum.kerbalspaceprogram.com/index.php?/topic/165170-0/)| ? | ? | ? | Under Consideration |
|<strike>[Cerillion](http://forum.kerbalspaceprogram.com/index.php?/topic/154315-0/)<br>[Cyran](http://forum.kerbalspaceprogram.com/index.php?/topic/139606-0/)<br>[Total Rebuild](http://forum.kerbalspaceprogram.com/index.php?/topic/154085-0/)| - | - | - | **Denied**<br>Compatibility will be handled<br>independently from GN |

**Comment by SamBelanger** [comment]
Add DD plz

**Comment by Sigma88** [comment]
DD has too many stars to fit in GN nicely

it would overwhelm the other packs
