### ISSUE TITLE
Proposed Planet Packs

### ISSUE THREAD

**Issue by Sigma88** [Sigma88/Galactic-Neighborhood#47]
| Planet Pack | Star Name | Star Type | Analogue | Status |
|--------------|-------------|-----------|------------|--------|
|[Imperial Planet Pack](https://forum.kerbalspaceprogram.com/index.php?/topic/165170-0/)| ? | ? | ? | Under Consideration |
|[Whirligig World](https://forum.kerbalspaceprogram.com/index.php?/topic/166563-0/)| ? | ? | ? | Under Consideration |
|<strike>[Cerillion](http://forum.kerbalspaceprogram.com/index.php?/topic/154315-0/)<br>[Cyran](http://forum.kerbalspaceprogram.com/index.php?/topic/139606-0/)<br>[Total Rebuild](http://forum.kerbalspaceprogram.com/index.php?/topic/154085-0/)| - | - | - | **Denied**<br>Compatibility will be handled<br>independently from GN |

**Comment by dkera** [comment]
DoubleDouble
