### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by Topside08** [Sigma88/Galactic-Neighborhood#50]
It says to add a _GalacticNeighborhood_ folder to _PluginData_ but I only have a _Plugins_ folder in my install do I have to make a _PluginData_ folder or does it go in _Plugins_

**Comment by Topside08** [comment]
Alright I figured it out you have to create the PluginData folder if it isn't there.

**Comment by Sigma88** [comment]
Yes, I will specify that in the wiki just in case it is confusing if I don't.

Thanks for asking :+1:
