### ISSUE TITLE
How to add planet pack compatibility?

### ISSUE THREAD

**Issue by Clamp-o-Tron** [Sigma88/Galactic-Neighborhood#53]
Galactic Neighborhood has been around for a long time, and many planet packs have been established since most of this code was written. With the inactivity surrounding this project and Sigma’s migration from the forums, not much work has been done. I can help with this. The only problem is that I don’t know the language or how this code works. If someone could tell me how, I would be able to add compatibility. Thanks for the instructions and all the work you have done of this mod!

**Comment by Sigma88** [comment]
I stopped updating this mod because there was noone expressing interest in it.

If you have a specific mod in mind I am happy to accept requests. I always manage all the compatibility myself since there are a lot of issues that needs to be considered.

I can't promise you an ETA on the next update, but the latest release is up to date with the latest kopernicus (1.7.3-2)

**Comment by Clamp-o-Tron** [comment]
Thanks for the fast response! I would particularly like The World Beyond, Interstellar Adventure Revived, and Kerbal Galaxy 3. Those are all huge mods, so I couldn’t expect anyone to finish all of these. Thanks again for your continuing work on this mod!

**Comment by Sigma88** [comment]
I have already looked into those mods however they have a completely different approach to galaxies and it basically makes it impossible for me to integrate them into GN.

I can't 100% exclude it, but it would not be an easy task

**Comment by Clamp-o-Tron** [comment]
OK. Is it then possible to integrate them into one save without causing glitchiness?

**Comment by Sigma88** [comment]
I don't think you will be able to load the game at all with GN and any of those three.

There are too many factors to account for when mixing multiple galaxy mods and those mods have a structure that is fundamentally in contrast with each other and with GN

**Comment by Clamp-o-Tron** [comment]
OK! Thanks for helping a newbie out!

**Comment by Clamp-o-Tron** [comment]
Sorry to reopen this (and maybe pester you) but I was wondering if this could be fixed by importing the planet and star data from those packs and putting it into a GN-compatible pack. Or in fact, just creating a clone of those packs with the GN structure.

**Comment by Sigma88** [comment]
I don't think it could work, not for packs of that size that require a huge galaxy setup.

GN is designed to be a "small" galaxy mod, if you look at the stars they are arranged in a shape that should remind of an "arm" of a spiral galaxy. and the idea is that each planet pack gets one star in this "Galactic Neighborhood"

**Comment by Clamp-o-Tron** [comment]
Could I have permission to create a fork to see if I can work on it? The final result won’t be very similar to the master branch, it will be more of a spin-off.

**Comment by Sigma88** [comment]
You can use modulemanager to make patches that integrate GN with any other galaxy mod. This is what I do with all the planet packs compatible with GN, I don't redistribute any of them, I just provide compatibility for them.

If you want to fork it for your personal use go ahead, but if you want to distribute stuff make sure you don't include anything from my mod

**Comment by Clamp-o-Tron** [comment]
Thanks for putting up with my stupid questions!
