### ISSUE TITLE
KSC Problem

### ISSUE THREAD

**Issue by 0xd1cf001e** [Sigma88/Galactic-Neighborhood#54]
![image](https://user-images.githubusercontent.com/41188403/71947331-86720280-3207-11ea-9c97-f4cf6ea4678e.png)

**Comment by Sigma88** [comment]
This is an issue linked to the reparenting of kerbin. It only shows up in that scene, when you launch a craft it will work fine.

I have tried fixing this issue but there doesn't seem to be a fix

**Comment by chengyufei** [comment]
OK thank you anyway。

**Comment by Sigma88** [comment]
you can still use the buttons on the side to enter the various buildings

It used to be not that bad, if I will update GN I will probably try to find a workaround

**Comment by 0xd1cf001e** [comment]
I think you can set the reference body of the stars to the sun, not the galactic core

**Comment by 0xd1cf001e** [comment]
Anyway, the orbit is hidden. No one can tell which is the galactic core.

**Comment by Sigma88** [comment]
Initially the idea was to have the interstellar space have referenceBody = Galactic Core

But at this point it's probably best to just have the sun be the center

**Comment by Sigma88** [comment]
Idk if GN will be updated to the current version of KSP, it's a huge project

**Comment by 0xd1cf001e** [comment]
I mean don't add a body called "Stock Sun", and don't reparent stock planets

**Comment by Sigma88** [comment]
yes that's what I mean by

>But at this point it's probably best to just have the sun be the center

**Comment by 0xd1cf001e** [comment]
ok
